name: V2Ray Config Collector

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect_configs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx[http2] beautifulsoup4 pydantic jdatetime aiofiles geoip2 rich

      - name: Run script
        run: |
          python main.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "action@github.com"
          git add -A
          if ! git diff --staged --quiet; then
            COMMIT_DATE=$(python -c "import jdatetime; now = jdatetime.datetime.now(); print(f\"{now.day} {jdatetime.date.j_months_en[now.month-1]}\")")
            COMMIT_TIME=$(TZ='Asia/Tehran' date "+%a %H:%M:%S")
            COMMIT_MESSAGE="🔄 Update V2Ray configs on $COMMIT_TIME $COMMIT_DATE"
            
            git commit -m "$COMMIT_MESSAGE"
            git push --force
          else
            echo "No changes to commit."
          fi
